debug = true
logLevel = "info"
defaultEntryPoints = ["http", "https"]

[api]
dashboard = true

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
            entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]
           [[entryPoints.https.tls.certificates]]
              certFile = "/certs/cert.crt"
              keyFile = "/certs/cert.key"

[docker]
endpoint = "unix:///var/run/docker.sock"

[[tls]]
  entryPoints = ["https"]
  [tls.certificate]
    certFile = "/certs/cert.crt"
    keyFile = "/certs/cert.key"
